"""Smoke tests for ``adidtc gen-dts``."""

import json
from pathlib import Path

import pytest
from click.testing import CliRunner

from adidt.cli.main import cli


@pytest.mark.parametrize(
    "board, platform, expected_name",
    [
        ("ad9081_fmc", "zcu102", "ad9081_zcu102"),
        ("ad9084_fmc", "vpk180", "ad9084_vpk180"),
    ],
)
def test_gen_dts_supported_combos_write_dts(
    tmp_path: Path, board: str, platform: str, expected_name: str
):
    runner = CliRunner()
    cfg = tmp_path / "cfg.json"
    cfg.write_text("{}")
    out = tmp_path / f"{expected_name}.dts"

    result = runner.invoke(
        cli,
        ["gen-dts", "-b", board, "-p", platform, "-c", str(cfg), "-o", str(out)],
    )
    assert result.exit_code == 0, result.output
    assert out.exists()
    content = out.read_text()
    assert "AUTOGENERATED BY PYADI-DT" in content
    assert expected_name in content
    assert "/dts-v1/;" in content


def test_gen_dts_unsupported_combo_errors():
    runner = CliRunner()
    with runner.isolated_filesystem():
        Path("cfg.json").write_text("{}")
        result = runner.invoke(
            cli, ["gen-dts", "-b", "daq2", "-p", "zcu102", "-c", "cfg.json"]
        )
    assert result.exit_code != 0
    assert "Supported combos" in result.output


def test_gen_dts_applies_reference_frequency(tmp_path: Path):
    runner = CliRunner()
    cfg = tmp_path / "cfg.json"
    # Use a non-default reference frequency; the hmc7044 node's clkin
    # frequency list in the rendered DTS should reflect it.
    cfg.write_text(json.dumps({"reference_frequency": 100_000_000}))
    out = tmp_path / "design.dts"

    result = runner.invoke(
        cli,
        [
            "gen-dts",
            "-b",
            "ad9081_fmc",
            "-p",
            "zcu102",
            "-c",
            str(cfg),
            "-o",
            str(out),
        ],
    )
    assert result.exit_code == 0, result.output
    content = out.read_text()
    # HMC7044 pll1-clkin-frequencies should carry our override (100 MHz).
    assert "100000000" in content


def test_gen_dts_writes_default_output_path(tmp_path: Path, monkeypatch):
    runner = CliRunner()
    monkeypatch.chdir(tmp_path)
    cfg = tmp_path / "cfg.json"
    cfg.write_text("{}")

    result = runner.invoke(
        cli, ["gen-dts", "-b", "ad9081_fmc", "-p", "zcu102", "-c", str(cfg)]
    )
    assert result.exit_code == 0, result.output
    assert (tmp_path / "ad9081_zcu102.dts").exists()
