#!/bin/bash
# install.sh — install a systemd service for a labgrid exporter instance.
#
# Usage:
#   sudo ./install.sh <instance-name> <yaml-path> [OPTIONS]
#
# Example:
#   sudo ./install.sh nuc \
#       /home/tcollins/dev/lg-coordinator/lg_fmcdaq3_vcu118_exporter.yaml
#
# Options:
#   --coordinator ADDR   Coordinator host:port (default: 10.0.0.41:20408)
#   --user USER          Service runs as this user (default: $SUDO_USER or $USER)
#   --bin PATH           Path to labgrid-exporter binary
#                        (default: auto-detect via `command -v` as the user)
#   --ser2net-path DIR   Prepend DIR to the service PATH for ser2net discovery
#   --no-start           Don't enable/start the unit after install
#
# After install:
#   systemctl status labgrid-exporter@<name>
#   journalctl -u labgrid-exporter@<name> -f
#   sudo systemctl restart labgrid-exporter@<name>   # after a yaml change
#
set -euo pipefail

if [ "$EUID" -ne 0 ]; then
    echo "ERROR: must run as root (use sudo)" >&2
    exit 1
fi

usage() { sed -n '2,/^$/p' "$0"; }

if [ $# -lt 2 ]; then
    usage >&2
    exit 1
fi

NAME="$1"
YAML="$2"
shift 2

COORDINATOR="10.0.0.41:20408"
SERVICE_USER="${SUDO_USER:-$USER}"
EXPORTER_BIN=""
SER2NET_PATH=""
START=1

while [ $# -gt 0 ]; do
    case "$1" in
        --coordinator)   COORDINATOR="$2"; shift 2 ;;
        --user)          SERVICE_USER="$2"; shift 2 ;;
        --bin)           EXPORTER_BIN="$2"; shift 2 ;;
        --ser2net-path)  SER2NET_PATH="$2"; shift 2 ;;
        --no-start)      START=0; shift ;;
        -h|--help)       usage; exit 0 ;;
        *) echo "ERROR: unknown option $1" >&2; exit 1 ;;
    esac
done

if ! id "$SERVICE_USER" >/dev/null 2>&1; then
    echo "ERROR: user '$SERVICE_USER' does not exist" >&2
    exit 1
fi

if [ -z "$EXPORTER_BIN" ]; then
    EXPORTER_BIN=$(sudo -u "$SERVICE_USER" -H bash -lc 'command -v labgrid-exporter' || true)
    if [ -z "$EXPORTER_BIN" ]; then
        echo "ERROR: labgrid-exporter not on PATH for user $SERVICE_USER." >&2
        echo "       Install it (e.g., 'uv tool install labgrid') or pass --bin PATH." >&2
        exit 1
    fi
fi
if [ ! -x "$EXPORTER_BIN" ]; then
    echo "ERROR: $EXPORTER_BIN is not executable" >&2
    exit 1
fi

YAML_ABS=$(readlink -f "$YAML")
if [ ! -r "$YAML_ABS" ]; then
    echo "ERROR: YAML $YAML_ABS not readable" >&2
    exit 1
fi

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
UNIT_SRC="$SCRIPT_DIR/labgrid-exporter@.service"
UNIT_DST="/etc/systemd/system/labgrid-exporter@.service"
ENV_DST="/etc/default/labgrid-exporter-$NAME"

if [ ! -f "$UNIT_SRC" ]; then
    echo "ERROR: unit template not found at $UNIT_SRC" >&2
    exit 1
fi

BASE_PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
if [ -n "$SER2NET_PATH" ]; then
    SERVICE_PATH="$SER2NET_PATH:$BASE_PATH"
else
    SERVICE_PATH="$BASE_PATH"
fi

echo "Installing labgrid-exporter service:"
echo "   instance    : $NAME"
echo "   user        : $SERVICE_USER"
echo "   binary      : $EXPORTER_BIN"
echo "   coordinator : $COORDINATOR"
echo "   yaml        : $YAML_ABS"
echo "   PATH        : $SERVICE_PATH"
echo

sed "s|@SERVICE_USER@|$SERVICE_USER|g" "$UNIT_SRC" > "$UNIT_DST"
chmod 644 "$UNIT_DST"

cat > "$ENV_DST" <<EOF
# Generated by $(basename "$0") on $(date -Iseconds)
LG_EXPORTER_BIN=$EXPORTER_BIN
LG_COORDINATOR=$COORDINATOR
LG_EXPORTER_NAME=$NAME
LG_EXPORTER_YAML=$YAML_ABS
PATH=$SERVICE_PATH
EOF
chmod 644 "$ENV_DST"

systemctl daemon-reload

if [ "$START" -eq 1 ]; then
    systemctl enable --now "labgrid-exporter@$NAME"
    sleep 2
    systemctl --no-pager --full status "labgrid-exporter@$NAME" || true
else
    echo
    echo "Service installed but not started.  To start:"
    echo "   sudo systemctl enable --now labgrid-exporter@$NAME"
fi
