# adidt/xsa/merger.py
"""Merge a generated base DTS with ADI overlay nodes into a single DTS file."""

import logging
import re
import subprocess
import warnings
from pathlib import Path

_LABEL_RE = re.compile(r"^\s*([a-zA-Z_]\w*)\s*:\s*\w", re.MULTILINE)
_NODE_ADDR_RE = re.compile(r"@([0-9a-fA-F]+)\s*\{")
_NODE_LABEL_IN_SNIPPET_RE = re.compile(r"^\s*([a-zA-Z_]\w*)\s*:")
_BUS_NODE_RE = re.compile(r"^\s*&(?P<name>[a-zA-Z0-9_-]+)\s*\{")
_BUS_CHILD_HEADER_RE = re.compile(
    r"^(?P<indent>[ \t]*)(?:(?P<label>[a-zA-Z_]\w*)\s*:\s*)?"
    r"(?P<name>[a-zA-Z_][\w-]*?)@(?P<addr>[0-9A-Fa-fx]+)\s*\{\s*$",
    re.MULTILINE,
)
_INTERRUPTS_PROP_RE = re.compile(r"^\s*interrupts\s*=\s*<[^;]+>;\s*$", re.MULTILINE)
_INTERRUPT_PARENT_PROP_RE = re.compile(
    r"^\s*interrupt-parent\s*=\s*<[^;]+>;\s*$", re.MULTILINE
)
_log = logging.getLogger(__name__)

_BUS_LABELS = {"amba", "amba_pl", "axi", "ahb", "soc", "bus"}

# Ordered list of node categories with their human-readable section labels.
_SECTION_LABELS: list[tuple[str, str]] = [
    ("clkgens", "Clock Generators"),
    ("jesd204_rx", "JESD204 RX — transport, link and physical layers"),
    ("jesd204_tx", "JESD204 TX — transport, link and physical layers"),
    ("converters", "ADC / DAC / Transceiver PHY"),
]


def _section_comment(title: str, indent: str = "\t") -> str:
    """Return a single-line DTS block comment suitable as a section divider."""
    return f"{indent}/* --- {title} --- */"


def _file_header(name: str, kind: str) -> str:
    """Return a multi-line DTS file header block comment.

    Args:
        name: Board/profile name used as the document title.
        kind: ``"overlay"`` or ``"merged"`` — determines the usage hint.

    Returns:
        A ``/* ... */`` block comment string ready to prepend to a DTS file.
    """
    safe = name.replace("*/", "")
    if kind == "overlay":
        title = f"ADI Device Tree Overlay — {safe}"
        usage = (
            f" * Apply alongside the base DTB:\n"
            f" *   dtoverlay {safe}.dtso\n"
            f" *\n"
            f" * Or compile and load manually:\n"
            f" *   dtc -@ -I dts -O dtb -o {safe}.dtbo {safe}.dtso"
        )
    else:
        title = f"ADI Device Tree (merged) — {safe}"
        usage = f" * Compile with:\n *   dtc -I dts -O dtb -o system.dtb {safe}.dts"
    return (
        f"/*\n"
        f" * {title}\n"
        f" *\n"
        f" * Generated by pyadi-dt from XSA. Do not edit manually — re-run\n"
        f" * the pipeline to regenerate from the XSA source.\n"
        f" *\n"
        f"{usage}\n"
        f" */"
    )


class DtsMerger:
    """Merges ADI DTS node strings into a base DTS, producing overlay and merged outputs."""

    def merge(
        self,
        base_dts: str,
        nodes: dict[str, list[str]],
        output_dir: Path,
        name: str,
    ) -> tuple[str, str]:
        """Produce overlay (.dtso) and merged (.dts) and write files.

        Returns:
            (overlay_content, merged_content)
        """
        # Build a flat node list with section-divider comments interleaved.
        # Comments are only prepended to groups that contain bus-type nodes
        # (not starting with "&"), so top-only groups (e.g. &spi0 overlays)
        # don't inject a comment that would falsely populate bus_nodes.
        # Comment strings are harmless to conflict-detection logic (no label
        # or address match) and end up verbatim in the merged DTS output.
        all_nodes: list[str] = []
        for key, label in _SECTION_LABELS:
            group = nodes.get(key, [])
            if not group:
                continue
            has_bus_nodes = any(not n.lstrip().startswith("&") for n in group)
            if has_bus_nodes:
                all_nodes.append(_section_comment(label))
            all_nodes.extend(group)

        overlay = self._build_overlay(base_dts, nodes, name)
        merged = self._build_merged(
            base_dts, all_nodes, [output_dir, output_dir / "base"], name
        )

        (output_dir / f"{name}.dtso").write_text(overlay)
        merged_path = output_dir / f"{name}.dts"
        merged_path.write_text(merged)
        self._try_compile_dtb(merged_path)

        return overlay, merged

    def _scan_labels(self, dts: str) -> set[str]:
        """Return the set of all DTS node labels found in *dts*."""
        return set(_LABEL_RE.findall(dts))

    def _bus_label(self, labels: set[str]) -> str | None:
        """Return the best-matching AXI/AMBA bus label from *labels*, or None."""
        # Prefer "amba" (standard Xilinx/ARM bus label)
        if "amba" in labels:
            return "amba"
        # Fall back to other recognized bus labels in sorted order
        for label in sorted(labels & _BUS_LABELS):
            return label
        return None

    def _build_overlay(
        self, base_dts: str, nodes: dict[str, list[str]], name: str
    ) -> str:
        """Build a /dts-v1/ plugin overlay with a file header and section comments.

        Args:
            base_dts: Base DTS text, used only to detect the AXI/AMBA bus label.
            nodes: Categorised node dict (keys: ``"clkgens"``, ``"jesd204_rx"``,
                ``"jesd204_tx"``, ``"converters"``).
            name: Board/profile name embedded in the file header.

        Returns:
            A complete overlay DTS string starting with ``/dts-v1/;`` and
            ``/plugin/;``, followed by a file header and the annotated nodes.
        """
        bus_lines: list[str] = []
        top_lines: list[str] = []
        for key, label in _SECTION_LABELS:
            group = nodes.get(key, [])
            if not group:
                continue
            bus = [n for n in group if not n.lstrip().startswith("&")]
            top = [n for n in group if n.lstrip().startswith("&")]
            if bus:
                bus_lines.append(_section_comment(label, indent="\t"))
                bus_lines.extend(bus)
            if top:
                top_lines.append(_section_comment(label, indent=""))
                top_lines.extend(top)

        bus = self._bus_label(self._scan_labels(base_dts))
        lines = ["/dts-v1/;", "/plugin/;", ""]
        lines.append(_file_header(name, "overlay"))
        lines.append("")
        if bus and bus_lines:
            lines += [f"&{bus} {{"] + bus_lines + ["};"]
        elif bus_lines:
            lines += bus_lines
        lines += top_lines
        return "\n".join(lines) + "\n"

    def _build_merged(
        self, base_dts: str, all_nodes: list[str], include_dirs: list[Path], name: str
    ) -> str:
        """Return the merged DTS with a file header prepended.

        Args:
            base_dts: Raw base DTS text produced by sdtgen.
            all_nodes: Flat list of ADI node strings (may include section-comment
                strings interleaved between groups).
            include_dirs: Directories searched when resolving ``#include``
                directives referenced by *base_dts*.
            name: Board/profile name embedded in the file header.

        Returns:
            Complete merged DTS text with a ``/* ... */`` file header at the
            top, followed by the original DTS content with ADI nodes inserted.
        """
        content = self._merge_content(base_dts, all_nodes, include_dirs)
        return _file_header(name, "merged") + "\n" + content

    def _merge_content(
        self, base_dts: str, all_nodes: list[str], include_dirs: list[Path]
    ) -> str:
        """Insert *all_nodes* into *base_dts*, resolving conflicts and returning the merged DTS text."""
        merged = base_dts
        include_labels = self._scan_include_labels(base_dts, include_dirs)
        include_nodes = self._scan_include_nodes(base_dts, include_dirs)
        all_nodes = [
            self._augment_node_from_include(node, include_nodes) for node in all_nodes
        ]
        delete_directives = self._include_conflict_delete_directives(
            all_nodes, include_labels
        )
        if delete_directives:
            merged = self._insert_delete_directives(merged, delete_directives)

        # Replace conflicting address stubs
        for node in all_nodes:
            if node.lstrip().startswith("&"):
                bus_match = _BUS_NODE_RE.search(node)
                if bus_match:
                    bus_name = bus_match.group("name")
                    bus_children = self._extract_direct_children(node)
                    if bus_children:
                        merged = self._replace_bus_children(
                            merged, bus_name, bus_children
                        )
                continue
            label_match = _NODE_LABEL_IN_SNIPPET_RE.search(node)
            if label_match:
                label = label_match.group(1)
                label_conflict_re = re.compile(
                    r"[ \t]*"
                    + re.escape(label)
                    + r"\s*:\s*\w[\w-]*@[0-9a-fA-Fx]+\s*\{(?:[^{}]|\{[^}]*\})*\};",
                    re.DOTALL,
                )
                if label_conflict_re.search(merged):
                    warnings.warn(
                        f"Replaced existing base node with duplicate label '{label}'",
                        UserWarning,
                        stacklevel=2,
                    )
                    merged = label_conflict_re.sub("", merged)

            m = _NODE_ADDR_RE.search(node)
            if m:
                addr = m.group(1).lower()
                # Address 0x0 is common for unrelated CPU/memory stubs in base
                # trees; global replacement by unit-address can corrupt DTS.
                # Label-based replacement above already handles true duplicates.
                if int(addr, 16) == 0:
                    continue
                conflict_re = re.compile(
                    r"[ \t]+\w[\w-]*@"
                    + re.escape(addr)
                    + r"\s*\{(?:[^{}]|\{[^}]*\})*\};",
                    re.DOTALL,
                )
                if conflict_re.search(merged):
                    warnings.warn(
                        f"Replaced existing base node at address 0x{addr} with ADI node",
                        UserWarning,
                        stacklevel=2,
                    )
                    merged = conflict_re.sub("", merged)

        bus_nodes = [n for n in all_nodes if not n.lstrip().startswith("&")]
        top_nodes = [n for n in all_nodes if n.lstrip().startswith("&")]
        nodes_block = "\n".join(bus_nodes) + ("\n" if bus_nodes else "")
        top_nodes_block = "\n".join(top_nodes) + ("\n" if top_nodes else "")
        if not bus_nodes:
            return self._append_top_nodes(merged, top_nodes_block)
        merged_labels = self._scan_labels(merged)
        bus = self._bus_label(merged_labels)
        include_bus = self._bus_label(include_labels)

        if bus and f"{bus}:" in merged and bus_nodes:
            pattern = re.compile(
                r"(\s*" + re.escape(bus) + r"\s*:.*?\{)(.*?)(\n\s*\};)",
                re.DOTALL,
            )
            new_merged = pattern.sub(
                lambda m: m.group(1) + m.group(2) + "\n" + nodes_block + m.group(3),
                merged,
                count=1,
            )
            if new_merged != merged:
                return self._append_top_nodes(new_merged, top_nodes_block)
            warnings.warn(
                f"Could not insert into bus node '{bus}'; appending at root level",
                UserWarning,
                stacklevel=2,
            )
        elif include_bus and bus_nodes:
            block = f"&{include_bus} {{\n{nodes_block}}};\n"
            return self._append_top_nodes(
                merged.rstrip() + "\n\n" + block, top_nodes_block
            )
        else:
            warnings.warn(
                "No amba/axi bus label found; inserting ADI nodes under root node",
                UserWarning,
                stacklevel=2,
            )

        root_close = re.search(r"\n\};\s*$", merged)
        if root_close:
            insert_at = root_close.start()
            merged_with_bus = (
                merged[:insert_at] + "\n" + nodes_block + merged[insert_at:]
            )
            return self._append_top_nodes(merged_with_bus, top_nodes_block)

        warnings.warn(
            "Root node close not found; appending ADI nodes at file end",
            UserWarning,
            stacklevel=2,
        )
        return self._append_top_nodes(
            merged.rstrip() + "\n\n" + nodes_block, top_nodes_block
        )

    def _brace_depth(self, text: str, start: int, end: int) -> int:
        """Return the net brace depth change in *text[start:end]*."""
        depth = 0
        for ch in text[start:end]:
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
        return depth

    def _extract_direct_children(self, node: str) -> list[tuple[str | None, str]]:
        """Return ``(label, unit_address)`` pairs for each direct child node in *node*."""
        open_brace = node.find("{")
        if open_brace == -1:
            return []
        children: list[tuple[str | None, str]] = []
        for match in _BUS_CHILD_HEADER_RE.finditer(node):
            if match.start() < open_brace:
                continue
            if self._brace_depth(node, open_brace + 1, match.start()) != 0:
                continue
            children.append((match.group("label"), match.group("addr").lower()))
        return children

    def _replace_bus_children(
        self, merged: str, bus_name: str, children: list[tuple[str | None, str]]
    ) -> str:
        """Remove existing child nodes of *bus_name* that match *children* by label or address."""
        if not children:
            return merged

        # First try reference form (&spi0 { ... }), then label-definition form
        # (spi0: spi@... { ... }) which appears in the base DTS proper.
        bus_re = re.compile(r"(?m)^([ \t]*)&" + re.escape(bus_name) + r"\s*\{")
        bus_match = bus_re.search(merged)
        if not bus_match:
            label_def_re = re.compile(
                r"(?m)^([ \t]*)"
                + re.escape(bus_name)
                + r"\s*:\s*\w[\w-]*@[0-9a-fA-Fx]+\s*\{"
            )
            bus_match = label_def_re.search(merged)
        if not bus_match:
            return merged

        open_idx = merged.find("{", bus_match.start())
        if open_idx == -1:
            return merged

        depth = 0
        close_idx = None
        for idx in range(open_idx, len(merged)):
            if merged[idx] == "{":
                depth += 1
            elif merged[idx] == "}":
                depth -= 1
                if depth == 0:
                    close_idx = idx
                    if idx + 1 < len(merged) and merged[idx + 1] == ";":
                        close_idx = idx + 1
                    break
        if close_idx is None:
            return merged

        bus_block_start = bus_match.start()
        bus_block_end = close_idx + 1
        bus_block = merged[bus_block_start:bus_block_end]
        open_in_block = bus_block.find("{")
        if open_in_block == -1:
            return merged

        remove_ranges: list[tuple[int, int]] = []
        for child_match in _BUS_CHILD_HEADER_RE.finditer(bus_block):
            if (
                self._brace_depth(bus_block, open_in_block + 1, child_match.start())
                != 0
            ):
                continue
            label = child_match.group("label")
            addr = child_match.group("addr").lower()
            should_remove = any(
                (spec_label is not None and spec_label == label) or spec_addr == addr
                for spec_label, spec_addr in children
            )
            if not should_remove:
                continue

            node_start = child_match.start()
            depth_child = 0
            node_end = None
            for node_idx in range(child_match.end() - 1, len(bus_block)):
                if bus_block[node_idx] == "{":
                    depth_child += 1
                elif bus_block[node_idx] == "}":
                    depth_child -= 1
                    if depth_child == 0:
                        node_end = node_idx + 1
                        if node_end < len(bus_block) and bus_block[node_end] == ";":
                            node_end += 1
                        break
            if node_end is None:
                continue
            remove_ranges.append((node_start, node_end))

        if not remove_ranges:
            return merged

        remove_ranges = sorted(set(remove_ranges), reverse=True)
        modified_block = bus_block
        for start, end in remove_ranges:
            if (
                start > 0
                and modified_block[start - 1] == "\n"
                and end < len(modified_block)
                and modified_block[end] == "\n"
            ):
                start -= 1
            modified_block = modified_block[:start] + modified_block[end:]

        warnings.warn(
            f"Replaced existing SPI bus child node(s) on {bus_name}",
            UserWarning,
            stacklevel=2,
        )
        return merged[:bus_block_start] + modified_block + merged[bus_block_end:]

    def _append_top_nodes(self, merged: str, top_nodes_block: str) -> str:
        """Append top-level reference nodes (``&label { ... }``) after the main DTS body."""
        if not top_nodes_block.strip():
            return merged
        return merged.rstrip() + "\n\n" + top_nodes_block

    def _include_conflict_delete_directives(
        self, nodes: list[str], include_labels: set[str]
    ) -> list[str]:
        """Return ``/delete-node/`` directives for ADI nodes whose labels clash with included nodes."""
        if not include_labels:
            return []
        directives: list[str] = []
        for node in nodes:
            label_match = _NODE_LABEL_IN_SNIPPET_RE.search(node)
            if label_match and label_match.group(1) in include_labels:
                label = label_match.group(1)
                warnings.warn(
                    f"Replaced included node with duplicate label '{label}'",
                    UserWarning,
                    stacklevel=3,
                )
                directives.append(f"/delete-node/ &{label};")
        return directives

    def _insert_delete_directives(self, merged: str, directives: list[str]) -> str:
        """Insert *directives* into *merged* after the last ``#include`` line."""
        if not directives:
            return merged
        block = "\n".join(directives) + "\n"
        return self._insert_after_includes(merged, block)

    def _insert_after_includes(self, merged: str, block: str) -> str:
        """Insert *block* immediately after the last ``#include`` directive in *merged*."""
        include_line_re = re.compile(r'^\s*#include\s+"[^"]+"\s*$', re.MULTILINE)
        matches = list(include_line_re.finditer(merged))
        if matches:
            insert_at = matches[-1].end()
            return merged[:insert_at] + "\n" + block + merged[insert_at:]
        dts_header_idx = merged.find("/dts-v1/;")
        if dts_header_idx != -1:
            line_end = merged.find("\n", dts_header_idx)
            if line_end != -1:
                return merged[: line_end + 1] + block + merged[line_end + 1 :]
        return block + merged

    def _scan_include_labels(self, base_dts: str, include_dirs: list[Path]) -> set[str]:
        """Recursively collect all node labels defined in files included by *base_dts*."""
        include_re = re.compile(r'^\s*#include\s+"([^"]+)"', re.MULTILINE)
        seen: set[str] = set()
        labels: set[str] = set()

        def walk(text: str) -> None:
            for match in include_re.findall(text):
                if match in seen:
                    continue
                seen.add(match)
                include_text = self._read_include_file(match, include_dirs)
                if include_text is not None:
                    labels.update(self._scan_labels(include_text))
                    walk(include_text)

        walk(base_dts)
        return labels

    def _scan_include_nodes(
        self, base_dts: str, include_dirs: list[Path]
    ) -> dict[str, str]:
        """Return a mapping of label -> node text for all labelled nodes in included files."""
        include_re = re.compile(r'^\s*#include\s+"([^"]+)"', re.MULTILINE)
        seen: set[str] = set()
        nodes: dict[str, str] = {}
        label_node_re = re.compile(
            r"^\s*([a-zA-Z_]\w*)\s*:\s*\w[\w-]*@[0-9a-fA-Fx]+\s*\{(?:[^{}]|\{[^}]*\})*\};",
            re.MULTILINE | re.DOTALL,
        )

        def walk(text: str) -> None:
            for match in include_re.findall(text):
                if match in seen:
                    continue
                seen.add(match)
                include_text = self._read_include_file(match, include_dirs)
                if include_text is None:
                    continue
                for node_match in label_node_re.finditer(include_text):
                    label = node_match.group(1)
                    nodes[label] = node_match.group(0)
                walk(include_text)

        walk(base_dts)
        return nodes

    def _augment_node_from_include(
        self, node: str, include_nodes: dict[str, str]
    ) -> str:
        """Copy missing ``interrupts`` / ``interrupt-parent`` props from the matching include node."""
        label_match = _NODE_LABEL_IN_SNIPPET_RE.search(node)
        if not label_match:
            return node
        include_node = include_nodes.get(label_match.group(1))
        if include_node is None:
            return node

        additions: list[str] = []
        if "interrupts" not in node:
            prop = _INTERRUPTS_PROP_RE.search(include_node)
            if prop:
                additions.append(prop.group(0).strip())
        if "interrupt-parent" not in node:
            prop = _INTERRUPT_PARENT_PROP_RE.search(include_node)
            if prop:
                additions.append(prop.group(0).strip())
        if not additions:
            return node

        insertion = "".join(f"\n\t\t{line}" for line in additions)
        return re.sub(r"\n\s*\};\s*$", f"{insertion}\n\t}};", node)

    def _read_include_file(
        self, include_name: str, include_dirs: list[Path]
    ) -> str | None:
        """Search *include_dirs* for *include_name* and return its text, or None if not found."""
        for base in include_dirs:
            path = base / include_name
            if path.exists():
                return path.read_text()
        return None

    def _try_compile_dtb(self, dts_path: Path) -> None:
        """Attempt to compile *dts_path* to a DTB via ``dtc``; logs a warning on failure."""
        dtb_path = dts_path.with_suffix(".dtb")
        try:
            compile_input = dts_path
            text = dts_path.read_text()
            if "#include" in text:
                cpp = self._find_tool("cpp")
                if cpp is None:
                    _log.info(
                        "cpp not found on PATH; skipping include-aware DTB compilation check"
                    )
                    return
                preprocessed = dts_path.with_suffix(".pp.dts")
                cpp_cmd = [
                    cpp,
                    "-P",
                    "-nostdinc",
                    "-undef",
                    "-x",
                    "assembler-with-cpp",
                    "-I",
                    str(dts_path.parent),
                    "-I",
                    str(dts_path.parent / "base"),
                    str(dts_path),
                    str(preprocessed),
                ]
                cpp_result = subprocess.run(
                    cpp_cmd,
                    capture_output=True,
                    text=True,
                    check=False,
                )
                if cpp_result.returncode != 0:
                    _log.warning("cpp preprocessing failed: %s", cpp_result.stderr)
                    return
                compile_input = preprocessed
            result = subprocess.run(
                [
                    "dtc",
                    "-I",
                    "dts",
                    "-O",
                    "dtb",
                    "-o",
                    str(dtb_path),
                    str(compile_input),
                ],
                capture_output=True,
                text=True,
                check=False,
            )
            if result.returncode != 0:
                _log.warning("dtc compilation failed: %s", result.stderr)
        except FileNotFoundError:
            _log.info("dtc not found on PATH; skipping DTB compilation")

    def _find_tool(self, name: str) -> str | None:
        """Return the full path of *name* on PATH, or None if not found."""
        from shutil import which

        return which(name)
