"""PetaLinux integration — transform XSA pipeline overlay into system-user.dtsi."""

from __future__ import annotations

import re
from pathlib import Path


# PetaLinux versions >= 2020.1 expect system-user.dtsi to include system-conf.dtsi
_SYSTEM_CONF_MIN_VERSION = "2020.1"

# ZynqMP PetaLinux DTG uses amba_pl for PL peripherals
_ZYNQMP_PLATFORMS = {
    "zcu102",
    "zcu104",
    "zcu106",
    "zcu111",
    "zcu208",
    "zcu216",
    "zu11eg",
}


class PetalinuxFormatter:
    """Transform XSA pipeline overlay content into PetaLinux system-user.dtsi."""

    def format_system_user_dtsi(
        self,
        overlay_content: str,
        *,
        platform: str | None = None,
        petalinux_version: str | None = None,
    ) -> str:
        """Convert overlay DTS content to a PetaLinux-compatible system-user.dtsi.

        Args:
            overlay_content: Overlay DTS string from ``DtsMerger._build_overlay``.
            platform: Target platform (e.g. ``"zcu102"``).  When the platform
                is ZynqMP-based, ``&amba`` references are rewritten to
                ``&amba_pl`` to match PetaLinux DTG conventions.
            petalinux_version: PetaLinux version string (e.g. ``"2024.1"``).
                When ``None`` or >= ``"2020.1"``, the output includes
                ``#include "system-conf.dtsi"``.  Pass a version below
                ``"2020.1"`` to omit the include.

        Returns:
            A system-user.dtsi string ready to drop into a PetaLinux project.
        """
        lines = overlay_content.splitlines()

        # Strip /dts-v1/; and /plugin/; directives
        lines = [ln for ln in lines if ln.strip() not in ("/dts-v1/;", "/plugin/;")]

        # Strip the file header comment block (/* ... */)
        lines = self._strip_header_comment(lines)

        # Strip leading blank lines
        while lines and not lines[0].strip():
            lines.pop(0)

        # Rewrite &amba to &amba_pl for ZynqMP platforms
        if platform and platform.lower() in _ZYNQMP_PLATFORMS:
            lines = [re.sub(r"^&amba\b", "&amba_pl", ln) for ln in lines]

        # Build output
        header = [
            "// SPDX-License-Identifier: GPL-2.0",
            "/*",
            " * system-user.dtsi — generated by pyadi-dt",
            " *",
            " * Drop this file into your PetaLinux project at:",
            " *   project-spec/meta-user/recipes-bsp/device-tree/files/",
            " */",
        ]

        if self._needs_system_conf(petalinux_version):
            header.append('#include "system-conf.dtsi"')

        header.append("")

        return "\n".join(header + lines)

    def generate_bbappend(self) -> str:
        """Return minimal device-tree.bbappend content for PetaLinux."""
        return 'FILESEXTRAPATHS:prepend := "${THISDIR}/files:"\n'

    @staticmethod
    def _strip_header_comment(lines: list[str]) -> list[str]:
        """Remove the first /* ... */ block comment from lines."""
        result: list[str] = []
        in_comment = False
        comment_done = False
        for ln in lines:
            if not comment_done and not in_comment and ln.strip().startswith("/*"):
                in_comment = True
                if "*/" in ln:
                    in_comment = False
                    comment_done = True
                continue
            if in_comment:
                if "*/" in ln:
                    in_comment = False
                    comment_done = True
                continue
            result.append(ln)
        return result

    @staticmethod
    def _needs_system_conf(petalinux_version: str | None) -> bool:
        """Return True if the PetaLinux version needs #include "system-conf.dtsi"."""
        if petalinux_version is None:
            return True
        try:
            parts = petalinux_version.split(".")
            major = int(parts[0])
            minor = int(parts[1]) if len(parts) > 1 else 0
            return (major, minor) >= (2020, 1)
        except (ValueError, IndexError):
            return True


def validate_petalinux_project(project_dir: Path) -> None:
    """Validate that *project_dir* has PetaLinux project structure.

    Raises:
        ValueError: If the expected directory layout is missing.
    """
    dt_files = (
        project_dir
        / "project-spec"
        / "meta-user"
        / "recipes-bsp"
        / "device-tree"
        / "files"
    )
    if not dt_files.is_dir():
        raise ValueError(
            f"Not a valid PetaLinux project: {project_dir}\n"
            f"Expected directory not found: {dt_files}\n"
            "Run 'petalinux-config --get-hw-description' first to initialize the project."
        )
