"""ADRV9009 + ZCU102 runtime overlay load/unload test.

Tests that a device tree overlay generated by the XSA pipeline can be:
1. Compiled from .dtso to .dtbo with external symbol preservation
2. Deployed to a running ZCU102 target
3. Loaded at runtime via configfs (/sys/kernel/config/device-tree/overlays/)
4. Verified by checking that IIO devices appear after loading
5. Unloaded by removing the configfs overlay directory
6. Verified that IIO devices disappear after unloading

Prerequisites:
    - LG_ENV pointing to an ADRV9009+ZCU102 labgrid environment
    - sdtgen and dtc on PATH
    - ZCU102 running Kuiper Linux with CONFIG_OF_OVERLAY=y
    - Board booted with a base DTB that does NOT include ADRV9009 nodes

Flow:
    XSA → XsaPipeline → .dtso → dtc -@ → .dtbo → deploy → load → verify → unload → verify
"""

from __future__ import annotations

import os
import shutil
from pathlib import Path

import pytest

from adidt.xsa.pipeline import XsaPipeline
from test.hw.hw_helpers import compile_dtso_to_dtbo, shell_out

PROFILE_NAME = "adrv9009_zcu102"
LG_ENV_PATH = os.environ.get("LG_ENV", "")
OVERLAY_NAME = "adrv9009_zcu102_xsa"
CONFIGFS_OVERLAYS = "/sys/kernel/config/device-tree/overlays"
DTBO_DEPLOY_PATH = f"/tmp/{OVERLAY_NAME}.dtbo"

HERE = Path(__file__).parent
OUT_DIR = HERE / "output_adrv9009_overlay"


def _require_env() -> None:
    if not LG_ENV_PATH:
        pytest.skip("set LG_ENV to run this hardware test")
    if not Path(LG_ENV_PATH).exists():
        pytest.skip(f"labgrid env file missing: {LG_ENV_PATH}")


def _require_tools() -> None:
    if shutil.which("sdtgen") is None:
        pytest.skip("sdtgen not found on PATH")
    if shutil.which("dtc") is None:
        pytest.skip("dtc not found on PATH")


# ---------------------------------------------------------------------------
# Unit tests (no hardware required)
# ---------------------------------------------------------------------------


class TestOverlayGeneration:
    """Test that the pipeline generates a valid .dtso and it compiles to .dtbo."""

    def test_pipeline_generates_dtso(self, tmp_path):
        """XsaPipeline produces a .dtso overlay file."""
        from test.xsa.kuiper_release import download_project_xsa

        xsa_path = download_project_xsa(
            release=os.environ.get("ADI_KUIPER_BOOT_RELEASE", "2023_r2"),
            project_dir="zynqmp-zcu102-rev10-adrv9009",
            cache_dir=tmp_path / "cache",
            output_dir=tmp_path / "xsa",
        )
        if not xsa_path.exists():
            pytest.skip("could not download ADRV9009 ZCU102 XSA")

        result = XsaPipeline().run(
            xsa_path=xsa_path,
            cfg={},
            output_dir=tmp_path / "out",
            profile=PROFILE_NAME,
            sdtgen_timeout=300,
        )
        overlay = result["overlay"]
        assert overlay.exists(), f"overlay not generated: {overlay}"

        text = overlay.read_text()
        assert "/plugin/;" in text, "overlay missing /plugin/ directive"
        assert "adi,adrv9009" in text or "adrv9009" in text, (
            "overlay missing ADRV9009 compatible"
        )

    @pytest.mark.skipif(shutil.which("dtc") is None, reason="dtc not found on PATH")
    def test_dtso_compiles_to_dtbo(self, tmp_path):
        """A generated .dtso compiles to .dtbo with dtc -@."""
        from test.xsa.kuiper_release import download_project_xsa

        xsa_path = download_project_xsa(
            release=os.environ.get("ADI_KUIPER_BOOT_RELEASE", "2023_r2"),
            project_dir="zynqmp-zcu102-rev10-adrv9009",
            cache_dir=tmp_path / "cache",
            output_dir=tmp_path / "xsa",
        )
        if not xsa_path.exists():
            pytest.skip("could not download ADRV9009 ZCU102 XSA")

        result = XsaPipeline().run(
            xsa_path=xsa_path,
            cfg={},
            output_dir=tmp_path / "out",
            profile=PROFILE_NAME,
            sdtgen_timeout=300,
        )

        dtbo = tmp_path / "out" / f"{OVERLAY_NAME}.dtbo"
        compile_dtso_to_dtbo(result["overlay"], dtbo)
        assert dtbo.exists(), f"dtbo not generated: {dtbo}"
        assert dtbo.stat().st_size > 100, "dtbo suspiciously small"


# ---------------------------------------------------------------------------
# Hardware tests (require labgrid + live ZCU102)
# ---------------------------------------------------------------------------


@pytest.mark.lg_feature(["adrv9009", "zcu102"])
class TestOverlayLoadUnload:
    """Runtime overlay load/unload on a live ZCU102 target.

    Requires the board to be booted with a base Kuiper DTB that does NOT
    include ADRV9009 nodes.  The overlay adds them at runtime via configfs.
    """

    @pytest.fixture(autouse=True)
    def _require_hardware(self):
        _require_env()
        _require_tools()

    @pytest.fixture(scope="class")
    def overlay_dtbo(self, tmp_path_factory):
        """Generate and compile the ADRV9009 overlay .dtbo."""
        from test.xsa.kuiper_release import download_project_xsa

        tmp = tmp_path_factory.mktemp("overlay")
        xsa_path = download_project_xsa(
            release=os.environ.get("ADI_KUIPER_BOOT_RELEASE", "2023_r2"),
            project_dir="zynqmp-zcu102-rev10-adrv9009",
            cache_dir=tmp / "cache",
            output_dir=tmp / "xsa",
        )
        if not xsa_path.exists():
            pytest.skip("could not download ADRV9009 ZCU102 XSA")

        out_dir = tmp / "out"
        result = XsaPipeline().run(
            xsa_path=xsa_path,
            cfg={},
            output_dir=out_dir,
            profile=PROFILE_NAME,
            sdtgen_timeout=300,
        )

        dtbo = out_dir / f"{OVERLAY_NAME}.dtbo"
        compile_dtso_to_dtbo(result["overlay"], dtbo)
        return dtbo

    def test_configfs_overlay_support(self, board):
        """Verify the target kernel has configfs overlay support."""
        shell = board.target.get_driver("ADIShellDriver")
        result = shell_out(
            shell, f"test -d {CONFIGFS_OVERLAYS} && echo OK || echo MISSING"
        )
        assert "OK" in result, (
            f"configfs overlay directory not found at {CONFIGFS_OVERLAYS}. "
            "Ensure CONFIG_OF_OVERLAY=y in the kernel config."
        )

    def test_load_overlay(self, board, overlay_dtbo):
        """Load the ADRV9009 overlay via configfs and verify IIO devices appear."""
        shell = board.target.get_driver("ADIShellDriver")

        # Deploy .dtbo to target
        # (Assumes SSH or file transfer is available via the board driver)
        ssh = board.target.get_driver("SSHDriver")
        ssh.put(str(overlay_dtbo), DTBO_DEPLOY_PATH)

        # Ensure overlay is not already loaded
        shell_out(shell, f"rmdir {CONFIGFS_OVERLAYS}/{OVERLAY_NAME} 2>/dev/null; true")

        # Load overlay
        shell_out(shell, f"mkdir -p {CONFIGFS_OVERLAYS}/{OVERLAY_NAME}")
        result = shell_out(
            shell,
            f"echo -n {DTBO_DEPLOY_PATH} > {CONFIGFS_OVERLAYS}/{OVERLAY_NAME}/path 2>&1; echo RC=$?",
        )
        assert "RC=0" in result, f"overlay load failed: {result}"

        # Wait for driver probe
        import time

        time.sleep(5)

        # Verify IIO devices appeared
        iio_names = shell_out(
            shell, "cat /sys/bus/iio/devices/*/name 2>/dev/null; true"
        )
        print(f"IIO devices after overlay load: {iio_names}")

        adrv9009_found = any(
            name in iio_names
            for name in ["adrv9009-phy", "adrv9025-phy", "axi-adrv9009"]
        )
        assert adrv9009_found, (
            f"No ADRV9009 IIO device found after overlay load. "
            f"IIO devices present: {iio_names}"
        )

    def test_unload_overlay(self, board):
        """Unload the ADRV9009 overlay and verify IIO devices disappear."""
        shell = board.target.get_driver("ADIShellDriver")

        # Capture IIO devices before unload
        iio_before = shell_out(
            shell, "cat /sys/bus/iio/devices/*/name 2>/dev/null; true"
        )
        print(f"IIO devices before overlay unload: {iio_before}")

        # Unload overlay
        result = shell_out(
            shell,
            f"rmdir {CONFIGFS_OVERLAYS}/{OVERLAY_NAME} 2>&1; echo RC=$?",
        )
        assert "RC=0" in result, f"overlay unload failed: {result}"

        # Wait for driver removal
        import time

        time.sleep(3)

        # Verify ADRV9009 IIO devices are gone
        iio_after = shell_out(
            shell, "cat /sys/bus/iio/devices/*/name 2>/dev/null; true"
        )
        print(f"IIO devices after overlay unload: {iio_after}")

        adrv9009_still = any(
            name in iio_after
            for name in ["adrv9009-phy", "adrv9025-phy", "axi-adrv9009"]
        )
        assert not adrv9009_still, (
            f"ADRV9009 IIO device still present after overlay unload. "
            f"IIO devices: {iio_after}"
        )

    def test_reload_overlay(self, board, overlay_dtbo):
        """Reload the overlay after unload to verify repeatability."""
        shell = board.target.get_driver("ADIShellDriver")

        # Ensure clean state
        shell_out(shell, f"rmdir {CONFIGFS_OVERLAYS}/{OVERLAY_NAME} 2>/dev/null; true")

        # Reload
        shell_out(shell, f"mkdir -p {CONFIGFS_OVERLAYS}/{OVERLAY_NAME}")
        result = shell_out(
            shell,
            f"echo -n {DTBO_DEPLOY_PATH} > {CONFIGFS_OVERLAYS}/{OVERLAY_NAME}/path 2>&1; echo RC=$?",
        )
        assert "RC=0" in result, f"overlay reload failed: {result}"

        import time

        time.sleep(5)

        iio_names = shell_out(
            shell, "cat /sys/bus/iio/devices/*/name 2>/dev/null; true"
        )
        print(f"IIO devices after overlay reload: {iio_names}")

        adrv9009_found = any(
            name in iio_names
            for name in ["adrv9009-phy", "adrv9025-phy", "axi-adrv9009"]
        )
        assert adrv9009_found, (
            f"No ADRV9009 IIO device found after overlay reload. "
            f"IIO devices present: {iio_names}"
        )

        # Clean up
        shell_out(shell, f"rmdir {CONFIGFS_OVERLAYS}/{OVERLAY_NAME} 2>/dev/null; true")
