"""Pin ``examples/ad9081_fmc_zcu102.py`` against the canonical wiring.

The example mirrors ``_build_system`` in ``test_system_ad9081_zcu102``
(same converter config, same SPI buses, same JESD link wiring through
the named clock accessors).  This test runs the example as a subprocess
and asserts its DTS output equals what ``_build_system`` produces in
the same process.

Catches example drift the smoke test would miss: a future edit that
keeps the example runnable but changes the wiring (e.g., back to
numeric ``clk_out[i]`` indices) will produce a different DTS and fail
here, even if the smoke test still sees a valid overlay header.
"""

from __future__ import annotations

import importlib.util
import re
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
EXAMPLE = REPO_ROOT / "examples" / "ad9081_fmc_zcu102.py"
STRUCTURAL = (
    Path(__file__).resolve().parent / "test_system_ad9081_zcu102.py"
)

# The renderer stamps a "// AUTOGENERATED BY PYADI-DT <ISO timestamp>"
# header into each DTS.  Strip it so the comparison is stable.
_AUTOGEN_RE = re.compile(r"^// AUTOGENERATED BY PYADI-DT .*$", re.MULTILINE)


def _strip_header(dts: str) -> str:
    return _AUTOGEN_RE.sub("// AUTOGENERATED BY PYADI-DT <stamp>", dts)


def _load_structural_module():
    spec = importlib.util.spec_from_file_location(
        "_test_system_ad9081_zcu102_for_parity", STRUCTURAL
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_example_dts_matches_structural_test() -> None:
    canonical = (
        _load_structural_module()._build_system().generate_dts()
    )
    example_stdout = subprocess.run(
        [sys.executable, str(EXAMPLE)],
        capture_output=True,
        text=True,
        timeout=60,
        check=True,
    ).stdout
    # The example sets ``name="ad9081_zcu102"`` while the structural
    # test uses ``name="ad9081_zcu102"`` as well; if either changes,
    # the comparison still holds because both share the same name.
    assert _strip_header(example_stdout.strip()) == _strip_header(
        canonical.strip()
    ), (
        "examples/ad9081_fmc_zcu102.py produced DTS that differs from "
        "test/devices/test_system_ad9081_zcu102.py::_build_system().  "
        "Either the example or the structural test drifted; bring them "
        "back into sync."
    )
