"""ADRV9009-ZU11EG XSA → generated DTB → fixed-JTAG Kuiper hardware test.

The board is physically strapped for JTAG.  ``BootZynqMPJTAG`` reconstructs the
production PMUFW/PL/BL31/U-Boot chain, explicitly selects SD boot, and verifies
a Kuiper shell.  This test then installs the DTB generated by pyadi-dt on the
SD boot partition, repeats the complete JTAG handoff, and verifies the live
kernel, JESD204 links, dual ADRV9009 PHYs, and RX data path.

The original SD DTB is backed up before replacement and restored in ``finally``
while the generated kernel is running.  A failed generated-DTB boot leaves the
backup on the FAT partition for recovery through BootZynqMPJTAG's RAM-Linux
recovery state.
"""

from __future__ import annotations

import hashlib
import shutil
from pathlib import Path
from typing import Any

import pytest

from adidt.xsa.config.profiles import ProfileManager
from test.hw._system_base import requires_lg
from test.hw.hw_helpers import (
    apply_kuiper_dtb_fixups,
    assert_jesd_links_data,
    assert_no_kernel_faults,
    assert_no_probe_errors,
    assert_rx_capture_valid,
    collect_dmesg,
    compile_dts_to_dtb,
    deploy_dtbo_via_shell,
    open_iio_context,
    shell_out,
)
from test.hw.xsa._overlay_spec import local_xsa_or_skip
from adidt.xsa.pipeline import XsaPipeline
from adidt.xsa.parse.topology import XsaParser


LG_FEATURES = ("adrv9009zu11eg", "adrv2crr-fmc")
_XSA_RESOLVER = local_xsa_or_skip("system_top_adrv9009_zu11eg.xsa")
_BOOT_MOUNT = "/mnt/pyadi-dt-boot"
_BOOT_DTB = f"{_BOOT_MOUNT}/system.dtb"
_BACKUP_DTB = f"{_BOOT_DTB}.pyadi-dt-backup"
_REMOTE_DTB = "/tmp/pyadi-dt-system.dtb"


def _board_cfg() -> dict[str, Any]:
    """Return the checked ZU11EG profile plus the real JESD framing."""
    cfg: dict[str, Any] = dict(ProfileManager().load("adrv9009_zu11eg")["defaults"])
    cfg["jesd"] = {
        "rx": {"F": 4, "K": 32, "M": 4, "L": 2, "Np": 16, "S": 1},
        "tx": {"F": 2, "K": 32, "M": 4, "L": 4, "Np": 16, "S": 1},
    }
    return cfg


def _build_dtb(tmp_path: Path) -> Path:
    if shutil.which("sdtgen") is None:
        pytest.fail("sdtgen not on PATH on the ZU11EG hardware runner")
    if shutil.which("dtc") is None:
        pytest.fail("dtc not on PATH on the ZU11EG hardware runner")

    xsa_path = _XSA_RESOLVER(tmp_path)
    topology = XsaParser().parse(xsa_path)
    assert topology.inferred_platform() == "zu11eg"
    assert len(topology.jesd204_rx) >= 2, "expected RX and observation-RX JESD cores"
    assert topology.jesd204_tx, "expected a TX JESD core"

    # Keep generated products inside pytest's private directory.  The runner
    # synchronizes the checkout between jobs, so repository-local output can
    # disappear while a long hardware handoff is in progress.
    out_dir = tmp_path / "output"
    out_dir.mkdir(parents=True, exist_ok=True)
    result = XsaPipeline().run(
        xsa_path=xsa_path,
        cfg=_board_cfg(),
        output_dir=out_dir,
        sdtgen_timeout=300,
        profile="adrv9009_zu11eg",
    )
    merged_dts = result["merged"]
    merged = merged_dts.read_text()
    for needle in (
        'compatible = "adrv9009-x2"',
        'compatible = "adi,hmc7044"',
        "axi_adrv9009_som_rx_jesd",
        "axi_adrv9009_som_obs_jesd",
        "axi_adrv9009_som_tx_jesd",
    ):
        assert needle in merged, f"required ZU11EG topology {needle!r} is missing"

    # Keep the artifact in pytest's private directory.  The XSA output tree is
    # shared by hardware jobs and may be cleaned while the first JTAG handoff
    # is running.
    dtb_path = tmp_path / "adrv9009_zu11eg.dtb"
    compile_dts_to_dtb(merged_dts, dtb_path)
    assert apply_kuiper_dtb_fixups(dtb_path), (
        "SDT output unexpectedly lacked /chosen/bootargs; review the Kuiper boot contract"
    )
    assert dtb_path.stat().st_size > 0
    return dtb_path


def _mount_boot(shell) -> None:
    shell_out(shell, f"mkdir -p {_BOOT_MOUNT}")
    result = shell_out(
        shell,
        f"mountpoint -q {_BOOT_MOUNT} || mount -t vfat -o rw,sync /dev/mmcblk0p1 {_BOOT_MOUNT}; echo RC=$?",
    )
    assert "RC=0" in result, f"failed to mount SD boot partition: {result}"


def _install_generated_dtb(shell, dtb_path: Path) -> None:
    """Transfer *dtb_path*, preserve the production DTB, and install it atomically."""
    # Stock Kuiper has neither rz/lrz nor rx, so ADIShellDriver.put() cannot
    # use XMODEM.  The shared base64/chunk transfer is transport-independent.
    deploy_dtbo_via_shell(shell, dtb_path, _REMOTE_DTB)
    local_sha = hashlib.sha256(dtb_path.read_bytes()).hexdigest()
    _mount_boot(shell)
    result = shell_out(
        shell,
        "set -e; "
        f"test -s {_BOOT_DTB}; "
        f"if test ! -e {_BACKUP_DTB}; then "
        f"prod_sha=$(sha256sum {_BOOT_DTB} | cut -d' ' -f1); "
        f"cp -p {_BOOT_DTB} {_BACKUP_DTB}.new; sync; "
        f'test "$(sha256sum {_BACKUP_DTB}.new | cut -d\' \' -f1)" = "$prod_sha"; '
        f"mv {_BACKUP_DTB}.new {_BACKUP_DTB}; sync; fi; "
        f"test -s {_BACKUP_DTB}; "
        f"cp {_REMOTE_DTB} {_BOOT_DTB}.new; "
        f"mv {_BOOT_DTB}.new {_BOOT_DTB}; sync; "
        f"sha256sum {_BOOT_DTB} | cut -d' ' -f1",
    ).strip()
    assert local_sha in result, f"installed DTB hash mismatch: {result!r}"
    shell_out(shell, f"umount {_BOOT_MOUNT}")


def _restore_production_dtb(shell) -> None:
    """Durably restore the original DTB before removing its backup."""
    _mount_boot(shell)
    result = shell_out(
        shell,
        "set -e; "
        f"if test -s {_BACKUP_DTB}; then "
        f"backup_sha=$(sha256sum {_BACKUP_DTB} | cut -d' ' -f1); "
        f"cp -p {_BACKUP_DTB} {_BOOT_DTB}.restore; sync; "
        f'test "$(sha256sum {_BOOT_DTB}.restore | cut -d\' \' -f1)" = "$backup_sha"; '
        f"mv {_BOOT_DTB}.restore {_BOOT_DTB}; sync; "
        f'test "$(sha256sum {_BOOT_DTB} | cut -d\' \' -f1)" = "$backup_sha"; '
        f"rm {_BACKUP_DTB}; sync; "
        f"test ! -e {_BACKUP_DTB}; "
        f"else test -s {_BOOT_DTB}; fi; echo RESTORE_OK",
    )
    assert "RESTORE_OK" in result, f"failed to restore production DTB: {result}"
    shell_out(shell, f"umount {_BOOT_MOUNT}")


def _reboot_to_production_shell(board, shell) -> None:
    """Power-cycle and prove the restored production DTB still reaches Kuiper."""
    board.transition("powered_off")
    board.target.deactivate(shell.console)
    board.transition("kuiper_shell")


def _recover_and_restore_production_dtb(board) -> None:
    """Restore the backup from RAM-rooted recovery when generated Linux fails."""
    # ``never_retry`` marks a strategy object broken after any failed handoff.
    # Recovery starts with an unconditional power-off, so reset only the local
    # state-machine bookkeeping before taking that deterministic path.
    shell = board.target.get_driver("ADIShellDriver")
    board.target.deactivate(shell)
    board.target.deactivate(shell.console)
    board.broken = None
    board.status = type(board.status).unknown
    board.transition("recovery_linux")
    recovery_shell = board.target.get_driver("ADIShellDriver")
    _restore_production_dtb(recovery_shell)
    _reboot_to_production_shell(board, recovery_shell)


@requires_lg
@pytest.mark.lg_feature(list(LG_FEATURES))
def test_adrv9009_zu11eg_generated_dtb_boots_via_jtag(board, tmp_path):
    """Boot the pyadi-dt DTB through the complete physical JTAG handoff."""
    dtb_path = _build_dtb(tmp_path)

    # First boot the known-good production DTB so the generated DTB can be
    # transferred without an SD mux or a second out-of-band file server.
    board.transition("kuiper_shell")
    shell = board.target.get_driver("ADIShellDriver")
    transaction_started = False
    generated_boot_reached_shell = False
    uart_log = tmp_path / "generated-boot-uart.log"
    original_read = shell.console._read
    original_boot_timeout = board.kuiper_boot_timeout

    def _capture_uart(*args, **kwargs):
        data = original_read(*args, **kwargs)
        with uart_log.open("ab") as stream:
            stream.write(data)
        return data

    try:
        # Set this before installation: every failure after this point may have
        # created a backup or replaced system.dtb and must enter recovery.
        transaction_started = True
        _install_generated_dtb(shell, dtb_path)
        board.transition("powered_off")
        # The exporter closes the raw TCP connection across a power cycle, but
        # labgrid can otherwise leave SerialDriver marked active around that
        # closed socket.  Force a real deactivate/reactivate on the second
        # handoff so _activate_shell_bypass opens a fresh socket.
        board.target.deactivate(shell.console)
        shell.console._read = _capture_uart
        board.kuiper_boot_timeout = min(original_boot_timeout, 120)
        try:
            board.transition("kuiper_shell")
        except Exception:
            if uart_log.exists():
                tail = uart_log.read_bytes()[-16_384:].decode("utf-8", "replace")
                print(
                    f"GENERATED_BOOT_UART_TAIL_BEGIN\n{tail}\nGENERATED_BOOT_UART_TAIL_END"
                )
            raise
        finally:
            board.kuiper_boot_timeout = original_boot_timeout
            shell.console._read = original_read
        generated_boot_reached_shell = True
        shell = board.target.get_driver("ADIShellDriver")

        dmesg_txt = collect_dmesg(
            shell,
            tmp_path / "evidence",
            label="adrv9009_zu11eg_jtag",
            grep_pattern="adrv9009|hmc7044|jesd204|probe|failed|error",
        )
        assert_no_kernel_faults(dmesg_txt)
        assert_no_probe_errors(dmesg_txt)
        assert dmesg_txt.count("successfully initialized via jesd204-fsm") >= 2

        ctx, _ip = open_iio_context(shell)
        names = {device.name for device in ctx.devices if device.name}
        assert {"adrv9009-phy", "adrv9009-phy-b"} <= names
        for group in (
            {"axi-adrv9009-rx-hpc", "axi-adrv9009-rx-obs-hpc"},
            {"axi-adrv9009-tx-hpc"},
        ):
            assert group <= names, (
                f"missing IIO devices {sorted(group - names)}; present={sorted(names)}"
            )

        assert_jesd_links_data(
            shell,
            context="adrv9009_zu11eg_jtag",
            expected_rx_links=2,
            expected_tx_links=1,
        )
        assert_rx_capture_valid(
            ctx,
            ("axi-adrv9009-rx-hpc", "axi-adrv9009-rx-obs-hpc"),
            context="adrv9009_zu11eg_jtag",
        )
    finally:
        if transaction_started:
            if generated_boot_reached_shell:
                try:
                    _restore_production_dtb(shell)
                    _reboot_to_production_shell(board, shell)
                except Exception as direct_restore_error:
                    # The backup is retained until direct restoration is fully
                    # verified, so RAM Linux can safely retry the transaction.
                    _recover_and_restore_production_dtb(board)
                    raise direct_restore_error
            else:
                _recover_and_restore_production_dtb(board)
