from datetime import datetime

from jinja2 import Environment, FileSystemLoader
import os

from ..model.renderer import BoardModelRenderer


class layout:
    """Common Layout Class for DT generation templates."""

    includes = [""]

    template_filename = None
    output_filename = None
    use_plugin_mode = True  # Set to False for standalone DTS (not overlay)

    def gen_dt_preprocess(self, **kwargs):
        """Pre-process template context before rendering; override to inject extra variables."""
        return kwargs

    def gen_dt(self, **kwargs):
        """Generate the DT file from configuration structs.

        Raises:
            Exception: If the template file does not exist.
            Exception: If the output filename is not defined.

        Args:
            kwargs: Configuration structs.
        """
        if not self.template_filename:
            raise Exception("No template file specified")

        if not self.output_filename:
            raise Exception("No output file specified")

        # Import template
        loc = os.path.dirname(__file__)
        loc = os.path.join(loc, "..", "templates", "boards")
        file_loader = FileSystemLoader(loc)
        env = Environment(loader=file_loader)

        loc = os.path.join(self.template_filename)
        template = env.get_template(loc)

        kwargs = self.gen_dt_preprocess(**kwargs)
        # Construct the context for rendering the template
        render_context = {
            "base_dts_include": self.platform_config["base_dts_include"],
        }
        render_context.update(kwargs)  # Add all other kwargs

        # Generate DTS header based on plugin mode
        if self.use_plugin_mode:
            dts_header = "/dts-v1/;\n/plugin/;\n"
            output = dts_header + template.render(**render_context)
        else:
            # For standalone DTS files, don't add any header
            # The /dts-v1/; will be provided by the include chain or kernel build system
            output = template.render(**render_context)

        with open(self.output_filename, "w") as f:
            f.write(output)

        return self.output_filename

    def gen_dt_from_model(self, model, config_source="board_model"):
        """Render a :class:`~adidt.model.board_model.BoardModel` to a DTS file.

        This is the BoardModel-based alternative to :meth:`gen_dt`.  It renders
        the model via :class:`~adidt.model.renderer.BoardModelRenderer` and
        writes a standalone DTS file with SPDX header and metadata.

        Args:
            model: A :class:`~adidt.model.board_model.BoardModel` instance.
            config_source: Config source string for the metadata header.

        Returns:
            str: Path to the generated DTS file.
        """
        if not self.output_filename:
            raise Exception("No output file specified")

        nodes = BoardModelRenderer().render(model)
        all_nodes = []
        for key in ("clkgens", "jesd204_rx", "jesd204_tx", "converters"):
            all_nodes.extend(nodes.get(key, []))

        platform = getattr(self, "platform", "unknown")
        date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        base_include = ""
        if (
            hasattr(self, "platform_config")
            and "base_dts_include" in self.platform_config
        ):
            base_include = self.platform_config["base_dts_include"]

        lines = [
            "// SPDX-License-Identifier: GPL-2.0",
            f"// AUTOGENERATED BY PYADI-DT {date}",
            "/*",
            f" * Platform: {platform}",
            f" * Generated from: {config_source}",
            f" * Board model: {model.name}",
            " * Copyright (C) 2024 Analog Devices Inc.",
            " */",
            "",
        ]

        if self.use_plugin_mode:
            lines.extend(["/dts-v1/;", "/plugin/;", ""])
        elif base_include:
            lines.extend([f'#include "{base_include}"', ""])

        lines.append("\n\n".join(all_nodes))
        lines.append("")

        with open(self.output_filename, "w") as f:
            f.write("\n".join(lines))

        return self.output_filename

    def gen_dt_from_config(self, cfg, config_source="jif_solver"):
        """Generate DTS from raw solver config via BoardModel.

        Convenience method that calls :meth:`to_board_model` then
        :meth:`gen_dt_from_model`.  Subclasses must implement
        ``to_board_model(cfg)``.

        Args:
            cfg: Raw JIF solver configuration dict.
            config_source: Config source string for metadata.

        Returns:
            str: Path to the generated DTS file.
        """
        cfg = self.validate_and_default_fpga_config(cfg)
        model = self.to_board_model(cfg)
        return self.gen_dt_from_model(model, config_source=config_source)

    def map_jesd_subclass(self, name):
        """Map JESD204 subclass to integer.

        Args:
            name (str): JESD subclass name.

        Raises:
            Exception: Invalid subclass name.

        Returns:
            int: JESD subclass integer.
        """
        modes = ["jesd204a", "jesd204b", "jesd204c"]
        if name not in modes:
            raise Exception("JESD Subclass {} not supported".format(name))
        return modes.index(name)
