name: Unittests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - run: python -m pip install --upgrade pip
    - run: pip install -r requirements/requirements_dev.txt
    - run: pip install .
    - run: pytest -vs

  kuiper-test:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
    steps:
    - uses: actions/checkout@v4
    - run: apt update
    - run: apt install -y python3-pip python3-dev
    - run: python3 -m pip install --upgrade pip
    - run: pip install -r requirements/requirements_dev.txt
    - run: pip install .
    - run: pytest -vs
