name: Test on Kuiper64

permissions:
  contents: read

env:
  APP_NAME: pyadi-dt

on:
  pull_request:
    branches:
      - main

jobs:
  kuiper64-test:
    runs-on: ubuntu-24.04-arm
    env:
      CONTAINER_BASE_NAME: kuiper-container-basic
      DOCKER_IMAGE: aandrisa/kuiper_basic_64:latest
      IMAGE_ARCH: linux/arm64
      ARCHITECTURE: arm64
    name: Test on Kuiper64
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        path: ${{env.APP_NAME}}

    - name: Start persistent container
      run: |
        docker run -d \
            --platform ${{env.IMAGE_ARCH}} \
            --name ${{env.CONTAINER_BASE_NAME}}-${{env.ARCHITECTURE}} \
            -v "$GITHUB_WORKSPACE/${{env.APP_NAME}}:/workspace/${{env.APP_NAME}}" \
            -w /workspace/${{env.APP_NAME}} \
            ${{env.DOCKER_IMAGE}} tail -f /dev/null

    - name: Install Python dependencies
      run: |
        docker exec ${{env.CONTAINER_BASE_NAME}}-${{env.ARCHITECTURE}} sh -c "python3 -m pip install --upgrade pip &&  pip install '.[test]'"

    - name: Run tests
      run: |
        docker exec ${{env.CONTAINER_BASE_NAME}}-${{env.ARCHITECTURE}} sh -c "pytest -vs"
